# title: Adedayo Adegoke
logo: /assets/img/https://github.com/aadegoke74/aadegoke74.github.io/blob/main/Adedayo/Adedayo.PNG
description: Adedayo Data Science Portfolio
show_downloads: true
theme: jekyll-theme-minimal
